### ISSUE TITLE
Add utility to run exercise tests on premade exercise solutions

### ISSUE THREAD

**Issue by thorbjornwolf** [ines/spacy-course#10]
Issues #7 and #9 both pertain to broken exercise tests.

In this issue, I'd like to suggest that we automate away the boring part of checking that the exercise solutions pass their tests.

I haven't yet grokked how the student solutions are put together with the exercise tests, but it looks like the test has access to both the student code as a string, and to the variable defined within. Perhaps we could leverage that pre-made combination, just substituting the student solution with the instructor solution files?

This is, of course, only if you think it'll be worth the effort. Luckily, the course is made so the student can just move past any broken tests :smile:

**Comment by ines** [comment]
Yes, I definitely agree! One reason why I set up the test framework like this (using a function `test()` for each test, separating out the files etc.) was that I was hoping we could find a way to automate this with pytest and automatically check the solution files against their fests.

You can find more details on how the tests are put together in the app [here](https://github.com/ines/spacy-course#how-it-works). Basically, we're replacing the `${solution}` with the solution code and `${test}` with the test code:
```
from wasabi import Printer
__msg__ = Printer()
__solution__ = """${solution}"""
${solution}

${test}
try:
    test()
except AssertionError as e:
    __msg__.fail(e)
```

So in the automated Python-based test scenario, the steps would have to look like this:

* Run the solution code.
* Load the solution file as a string and expose it as `__solution__`.
* Run the test.

Here's a naive and hacky approach but I think this could actually work:

1. Loop over the contents of `/exercises` and fetch all tests files and their matching solution files.
2. Load the `meta.json` and the file contents of the test and solution files and perform the substitutions in the `testTemplate`.
3. Write the resulting string to a Python file in a directory like `__tests__` (which we'll ignore in the `.gitignore`) etc.
4. Run `pytest` on it. Bonus if all previous steps can be performed automatically via a [pytest hook](https://docs.pytest.org/en/latest/reference.html#hooks).
