### ISSUE TITLE
Chapter 4, section 3-4: Training data labelling misses bare "iPhone"

### ISSUE THREAD

**Issue by thorbjornwolf** [ines/spacy-course#17]
Exercises [04_03](https://github.com/ines/spacy-course/blob/master/exercises/exc_04_03.py) and [04_04](https://github.com/ines/spacy-course/blob/master/exercises/exc_04_04.py) both miss the "iPhone" entity in the sentence "Your iPhone goes up to 11 today". I  first thought this was on purpose, to teach us something about inspecting the labels.
However, seeing section 7's [gadgets](https://github.com/ines/spacy-course/blob/master/exercises/gadgets.json#L6) file, it looks like the "iPhone" _is_ intended to be included :smile:

**Comment by ines** [comment]
Thanks! And it looks like the problem is actually in `04_04` and the pre-filled matcher code there. Instead of `"OP": "?"` (as the user was asked to correctly write in the previous exercise), it now says `"OP": "+"` (which would require that token pattern to match **1 or more times**).
