### ISSUE TITLE
[Typo] Chapter 2, section 7: PRONOUN before VERB

### ISSUE THREAD

**Issue by navneethc** [ines/spacy-course#18]
A minor typo in part 2 of the section 7 questions. 

> If a proper noun after a verb is found, print the token.text.

should be, given the original question:

> If a proper noun **before** a verb is found, print the token.text.

**Comment by ines** [comment]
Thanks a lot ! Looks like this was related to the same issue as #15.

**Comment by navneethc** [comment]
Sorry about that, I only went through the issues but not the PRs. Thank you for offering this course, BTW. :)
