### ISSUE TITLE
Missing json file

### ISSUE THREAD

**Issue by Shwetago** [ines/spacy-course#22]
iphone.json file is missing from the exercises folder. Please check it!

**Comment by ines** [comment]
Are you seeing an error somewhere?

The file is here:
* https://github.com/ines/spacy-course/blob/master/exercises/iphone.json (master)
* https://github.com/ines/spacy-course/blob/binder/exercises/iphone.json (binder)

**Comment by Shwetago** [comment]
I wasn't able to access this file earlier and it turns out I had an issue with my code. It's a silly mistake and I am sorry about that @ines. 
Thank you so much for such a great course!
