### ISSUE TITLE
Chapter 4.4 evaluates correct with no entities

### ISSUE THREAD

**Issue by natashawatkins** [ines/spacy-course#31]
<img width="859" alt="Screen Shot 2019-05-30 at 1 12 58 am" src="https://user-images.githubusercontent.com/21038129/58568874-6729f480-8278-11e9-8802-730ec6ea13d2.png">

I put `doc.ents` instead of `entities` but it was still marked correct

**Comment by ines** [comment]
Thanks! Looks like my tests for this one were very rudimentary – I probably started off with the basics and forogt to fill in the specific checks: https://github.com/ines/spacy-course/blob/master/exercises/test_04_04.py

The tests here should ideally be as detailed as those: https://github.com/ines/spacy-course/blob/master/exercises/test_04_10.py

**Comment by meghanabhange** [comment]
Hi,
Can I try to flesh out more detailed tests using the reference you've provided?

**Comment by ines** [comment]
@meghanabhange Hi and sorry, totally missed your comment! If you want to add some tests and submit a PR, that'd be great 💯
