### ISSUE TITLE
videos

### ISSUE THREAD

**Issue by bytearchive** [ines/spacy-course#36]
can we embed youtube or video links or playable audio in the slides?

**Comment by ines** [comment]
The slides use `reveal.js` and are written in Markdown – so you can also include any HTML tags. Images are all embedded using `<img>`, so a YouTube embed code or HTML5 audio player, Soundcloud embed etc. should work, too. [See here](https://raw.githubusercontent.com/ines/course-starter-python/master/slides/chapter1_01_introduction.md) for a simple example of the markup.

If you want to adapt the course frame work for your own content, check out the Python starter repo: https://github.com/ines/course-starter-python
