### ISSUE TITLE
Chapter 2 § 4 prose disagrees with code

### ISSUE THREAD

**Issue by JimDabell** [ines/spacy-course#40]
In the section entitled _"The Span object (2)"_, the prose states:

> To add an entity label to the span, we first need to look up the string in the string store. We can then provide it to the span as the label argument.

However the code just passes in the string directly:

> `span_with_label = Span(doc, 0, 2, label="GREETING")`

It seems like the code assumes spaCy 2.1 which added support for passing in a Unicode string but the prose was written before 2.1 was released?

**Comment by ines** [comment]
Thanks for the report and yes, you're correct. I thought I had fixed this, but I guess this one slipped through the cracks. 

(That change in spaCy was actually directly inspired by this course. I basically realised how annoying it was to explain this and that there wasn't really a good reason it worked this way. So we ended up changing it 😄 )
