### ISSUE TITLE
Chapter 1 q11 Matcher matches all text.

### ISSUE THREAD

**Issue by songproducer** [ines/spacy-course#42]
```
import spacy

# Import the Matcher
from spacy.matcher import Matcher

nlp = spacy.load("en_core_web_sm")
doc = nlp("New iPhone X release date leaked as Apple reveals pre-orders by mistake")

# Initialize the Matcher with the shared vocabulary
matcher = Matcher(nlp.vocab)

# Create a pattern matching two tokens: "iPhone" and "X"
pattern = [{"TEXT": "iPhone"}, {"TEXT": "X"}]

# Add the pattern to the matcher
matcher.add("IPHONE_X_PATTERN", None, pattern)

# Use the matcher on the doc
matches = matcher(doc)
print("Matches:", [doc[start:end].text for match_id, start, end in matches])

```

produces 
`Matches: ['New', 'iPhone', 'X', 'release', 'date', 'leaked', 'as', 'Apple', 'reveals', 'pre', '-', 'orders', 'by', 'mistake']`

Spacy version 2.0.16

**Comment by ines** [comment]
Looks like the spaCy version you're running locally is to old – try upgrading to v2.1.x+ 🙂

Also see #32 

> Hi! The course was built for spaCy v2.1.x, so you'll need the most recent version to make sure all of the examples run as expected.
>
> The `TEXT` key on the patterns (instead of `ORTH`) was added in v2.1.0. It was actually directly inspired by this course, because I realised that explaining why it's called `ORTH` was unnecessarily complicated and you should just be able to specify `TEXT` for `token.text` instead. Similarly, when creating a `Span` object, the `label` argument can now also be a string instead of only an integer ID. 
>
> Also, to give you some background on what's happening in your case: Because spaCy v2.0.x doesn't know the `TEXT` key, it ignores it. So each dict in the pattern is interpreted as `{}`, i.e. "any token".

**Comment by songproducer** [comment]
Thanks!
