### ISSUE TITLE
Chapter 1, section 5: Add instructions on installing `en_core_web_sm`

### ISSUE THREAD

**Issue by thorbjornwolf** [ines/spacy-course#5]
_Spun off from https://github.com/ines/spacy-course/issues/4#issuecomment-485139261_

In chapter 1, section 5, slide 3, the following code block appears for the first time:

```python
import spacy

nlp = spacy.load('en_core_web_sm')
```

I personally like to jot down code along with the slides, so this is where I got "challenged", as follows (details at the bottom of the comment):

```python
>>> import spacy
>>> nlp = spacy.load('en_core_web_sm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[virtualenv dir]/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "[virtualenv dir]/lib/python3.7/site-packages/spacy/util.py", line 136, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

Luckily, the answer is in the [spacy docs](https://spacy.io/models/en#en_core_web_sm), in the **INSTALLATION** box on the right: `$ python -m spacy download en_core_web_sm`

After doing so, and starting a new python session:

```python
>>> import spacy
>>> nlp = spacy.load('en_core_web_sm')
>>> 
```

:tada: :relaxed: 

My suggested solution would be to add the installation instructions in the slides, or no later than the interactive code in section 7 **Loading models**. Otherwise, people who also run spacy locally will have to look it up themselves... which is not a big deal, just a tiny bump in the road :-)

<details>

### virtualenv setup
```
$ python3.7 -m virtualenv tmp-venv
$ source tmp-venv/bin/activate
$ pip install spacy
```

### pip freeze output
```
$ pip freeze
blis==0.2.4
certifi==2019.3.9
chardet==3.0.4
cymem==2.0.2
idna==2.8
jsonschema==2.6.0
murmurhash==1.0.2
numpy==1.16.2
plac==0.9.6
preshed==2.0.1
requests==2.21.0
spacy==2.1.3
srsly==0.0.5
thinc==7.0.4
tqdm==4.31.1
urllib3==1.24.2
wasabi==0.2.1
```

### python version
```
$ python --version
Python 3.7.1
```
</details>

**Comment by ines** [comment]
Thanks and yes, that's a really good point! 

I've updated the slides to include a mention of the `spacy download` command and also added a sentence and link to the docs to the first exercise that loads the models.
