### ISSUE TITLE
Trouble setting up a working JS environment for the course

### ISSUE THREAD

**Issue by swartchris8** [ines/spacy-course#53]
First of all thanks for sharing this lovely course. 

I was going to play around with the course today but I am having trouble setting up the JS requirements on my Mac (node 10, node 12, node 14) and an Ubuntu (node 12) docker image, I am a JS novice so that could be the problem.

I went down a rabbit hole trying to get sharp installed which led me to try and bump sharp up from `sharp@0.21.3` based on https://github.com/gatsbyjs/gatsby/issues/13781
Next I played npm whack-a-mole with trying making sure all dependencies' sharp version gets bumped which led to other dependencies needing to be changed.

Is there a way to resolve all these dependencies in the JS world? Python packaging seems like heaven compared to what I had to go through.

I have managed to create a working Dockerfile with all the updated packages where I can run gatsby in dev mode and run the python tests - I will create a PR to merge these.

--- BELOW is my debugging process as a JS novice ---

On both my Mac  and the Ubuntu  docker image following:

```
npm install -g gatsby-cli  # Install Gatsby globally
npm install                # Install dependencies
```

During `npm install` installing `sharp@0.21.3` fails with an error like this:

```
> sharp@0.21.3 install /host/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.16.3 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/host/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:27:0:
../src/common.h:78:20: error: 'Handle' is not a member of 'v8'
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                    ^~~~~~
../src/common.h:78:37: error: expected primary-expression before '>' token
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
.
.
.
```

Then I used to hunt down dependencies using sharp and what version are coming through:
```
npm ls | grep -C 10 --color sharp
```

Then using npm-remote-ls looked for what the updated sharp version would be for example with gatsby-plugin-manifest:
```
npm-remote-ls gatsby-plugin-manifest@2.0.29 | grep sharp
```

Tried to harmonise the version bumps to use one version of sharp as multiple sharp versions seem to potentially cause challenges.

Finally I have tried to resolve all conflicts from the previous bumps. As a complete JS Novice I am not sure if my approach is sensible I will make a PR where you can review

**Comment by swartchris8** [comment]
Opened a PR with my changes, hope they are helpful https://github.com/ines/spacy-course/pull/54

**Comment by swartchris8** [comment]
Created a PR with the js changes & the docker setup which should allow running the repo with docker also updated readme bits with the docker options - https://github.com/ines/spacy-course/pull/55

**Comment by ines** [comment]
Thanks so much for your PR and sorry about the frustration. No idea what exactly went wrong in your case and why it's compiling sharp and/or why it's failing... unfortunately you can easily get stuck in a bad state with C extensions in JS. 

Gatsby is definitely the culprit here. If you get Gatsby to install (which I was hoping shouldn't be too tricky, since it's reasonably popular), the course should work fine.

> Is there a way to resolve all these dependencies in the JS world? Python packaging seems like heaven compared to what I had to go through.

I work with JS a lot and I never now how to do this properly, to be honest 😞

**Comment by ines** [comment]
Already went ahead and merged #55. Copying over my question in case this is something we can adjust later:

> I don't know Docker very well, so I can't really review that part of it. Is there a way we can fold that `config.env` file into the Makefile? Or is that a Docker convention and required? I'm always trying to reduce the number of files and configs etc.

**Comment by swartchris8** [comment]
Sure I will pull the config.env into the makefile. It is not a convention just a pattern I like to use. With just one env var it makes sense to pull it in.

**Comment by swartchris8** [comment]
Just a disclaimer I am not an expert in docker or makefiles either, I refactored the config.env into the makefile. Created a PR with the changes. After running `make build` running `make pytest` for python tests or `make gatsby-dev` to run the gatsby dev server via docker

**Comment by rongpenl** [comment]
Possibly related to `node-gyp` package. See https://github.com/nodejs/node-gyp/issues/1779.
