### ISSUE TITLE
French translation?

### ISSUE THREAD

**Issue by ajw-42** [ines/spacy-course#62]
Hi, is there a French translation for the course in progress? I looked through issues and PRs but might have missed something. If not, I'm happy to start working on this. Thanks for the great course!

**Comment by ines** [comment]
Yes, we already have someone working on French 🎉 But thanks for the offer, I'm sure we can always use some help with proofreading and testing everything. I can ping you on this thread once a French PR is up so you can check it out 🙂

**Comment by ines** [comment]
@ajw-42 See #75 🎉
