### ISSUE TITLE
Chapter 1 Lesson 9 requires student to name the entity iterator variable 'ent' -- unnecessarily

### ISSUE THREAD

**Issue by pipehat** [ines/spacy-course#63]
Submitting the code with the iterator named anything other than **ent** results in an error message saying "✘ Are you iterating over the entities?"

But the iterator name has no impact on the generated output and shouldn't matter.

Looks like the solution does in fact search for 'ent' explicitly as the var name currently.
https://github.com/ines/spacy-course/blob/master/exercises/en/test_01_09.py

**Comment by ines** [comment]
Thanks, good point! 👍 Made the test less strict in #64. (In exercise 1.8.2 it's okay, I guess, because the variable name is hard-coded in the example code already.)
