### ISSUE TITLE
Use Japanese  model in Japanese translation

### ISSUE THREAD

**Issue by tamuhey** [ines/spacy-course#67]
Since spacy has released Japanese model in [v2.3](https://github.com/explosion/spaCy/releases/tag/v2.3.0), it would be good to use the Japanese model in Japanese version of this course. (Now `en` model is used)
One of the contributors of the Japanese model @hiroshi-matsuda-rit agrees with this idea.
What do you think, @ines?

**Comment by ines** [comment]
Yes, that would be amazing! 🙏 Some of the exercises will probably need adjustments to make them work with Japanese text while getting the same objectives across, like different combinations of tokens, match patterns, example texts, plus examples that the model gets right reliably etc. That's also how we did it for German and Spanish. Some of the text examples ended up very different from the originals. 

I'm also happy to answer any questions or help (to the best of my abilities 😉)

**Comment by tamuhey** [comment]
@ines thanks!
When should we make Pull Requests?

1. After replacing everything with the Japanese model
2. Gradually submit PRs when some slides are updated

I'm more than happy to do latter, as I can't take off a large amount of time.

**Comment by ines** [comment]
Gradually submitting PRs is totally fine! If there are some examples that don't work well in Japanese or that show an NLP concept that's difficult to get across with Japanese text, we could also leave them in English.

You probably want to base the PR off #69, which updates the course to spaCy v2.3 and the new models. It's not ready yet, since some of the examples in Spanish need adjustments to make them work with the new models.

**Comment by hiroshi-matsuda-rit** [comment]
@tamuhey Sorry for late reply. I'd like to replace the Japanese examples with the results of the latest Japanese model.
@ines Could you tell me an appropriate base branch or PR which I'd replace Japanese examples?

**Comment by tamuhey** [comment]
@hiroshi-matsuda-rit I think the master is appropriate. Is this alright, @ines ?

**Comment by hiroshi-matsuda-rit** [comment]
@tamuhey Thanks. I'd like to start editing `chaters/ja/` and `excersizes/ja/*` on master branch. Which kind of IDE are you using for the `spacy-course` project?

**Comment by hiroshi-matsuda-rit** [comment]
@tamuhey It seems we need to translate the example files below. Actually, I do not have enough time for that translation works. Sorry.

excersizes/ja/
- backquotes.json
- capitals.json
- countries.json
- country_text.txt
- gadgets.json
- iphone.json
- tweets.json

**Comment by tamuhey** [comment]
@hiroshi-matsuda-rit 
I'm using VSCode, but why?

> It seems we need to translate the example files below. Actually, I do not have enough time for that translation works. Sorry.

I also don't have enough time to translate all of the files at once, but I can gradually commit.

**Comment by hiroshi-matsuda-rit** [comment]
> I'm using VSCode, but why?

Thank you. I'd like to use same environment.

May I start discussing abuot how to share the translation tasks?
I've forked spacy-course on my account. https://github.com/hiroshi-matsuda-rit/spacy-course
Shall we use it for this issue?

In addition to the files which I listed above, we should add some Japanese specific files like `exercises/zh/exc_01_02_04.py`.
Could you list the required files? @tamuhey

**Comment by tamuhey** [comment]
> Thank you. I'd like to use same environment.
Thanks!

> Shall we use it for this issue?
All right!

> Could you list the required files?
OK!
