### ISSUE TITLE
Auto-format solution code with Black in testTemplate

### ISSUE THREAD

**Issue by ines** [ines/spacy-course#8]
@thorbjornwolf suggested in #7:

> Just a side-thought: Could it be interesting to use [Black](https://github.com/ambv/black) to normalize the solution code formatting before checking it? I see this test checks against the two main string quotes `"` and `'`: if that is a recurring thing, Black might help by forcing alllll the code to adhere to a certain, deterministic formatting choice. On the other hand, applying it just might increase complexity, and may reduce the readability of the tests 🤷‍♂️

I replied:

> Yessss, so cool you mentioned this – I actually had the exact same idea yesterday! 👍 This would definitely make it so much easier to validate the string code, because we can make more assumptions about it – and the user could still write their code however they want to. I'll need to play around with this a bit, though, to make sure there are no unintended side-effects (and how to best do it from within Python – I've only ever used Black via a plugin or on the command line before).

**Comment by thorbjornwolf** [comment]
Looks like [`black.format_str()`](https://black.readthedocs.io/en/stable/reference/reference_functions.html#black.format_str) is what one uses on python strings:

```python
In [1]: inp = """
   ...: import   spacy
   ...: nlp = spacy.load('en_core_web_sm'
   ...: )
   ...: """

In [2]: import black

In [3]: out = black.format_str(inp, line_length=88)

In [4]: print(out)

import spacy

nlp = spacy.load("en_core_web_sm")

```

It can become a problem that Black and its API is still in beta. But I guess that's why we pin dependencies :smile:
