### ISSUE TITLE
Issue with matcher in Excercise 1.12.2

### ISSUE THREAD

**Issue by gonmalo** [ines/spacy-course#81]
The following line of code and the instructions for this exercise may be wrong. As seen in the attached screenshot the target words are tagged as "INTJ" 

https://github.com/ines/spacy-course/blob/90feb4983573db71163ffda56d8fea78a02d747f/exercises/es/solution_01_12_02.py#L15
![spacy_basics](https://user-images.githubusercontent.com/4744675/89109133-7d978700-d40c-11ea-82ef-1553e9e2555d.PNG)

IMO, the idea was to match proper nouns and the example could be fine, meaning the issue is on the Spacy POS tagger. I may be missing something, so certainly, someone can determine if the POS tagger needs to be fixed or the example updated.

Regards
-Gon

**Comment by javiersefer** [comment]
Hummm, I tryed several sentences like:

> el juego se llama Fornite

But I get:

`el          DET       det       
juego       NOUN      nsubj     
se          PRON      obj       
llama       VERB      ROOT      
Fornite     INTJ      obj     `

Even if I try with different known names like: Minecraft, Quake, ... I can not get the PROPN, always I get the INTJ. I also tryed another kind of simple sentences with software or videogames names and get the same result.

> la empresa se llama Apple

`la          DET       det
empresa     NOUN      nsubj     
se          PRON      obj       
llama       VERB      ROOT      
Apple       INTJ      obj   `

> El jefe se llama Antonio

`El          DET       det       
jefe        NOUN      nsubj     
se          PRON      obj       
llama       VERB      ROOT      
Antonio     INTJ      obj`

I think this could be important to check.
